# -*- coding: utf-8 -*-
"""Fundamentos de IA 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLZPeBb22T7wBk1nfLH1hiyZqGTqR8am
"""

import pandas as pd
from google.colab import drive
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

drive.mount('/content/drive/')
jugadores = pd.read_excel('drive/MyDrive/Dataset_Jugadores.xlsx')
jugadores

pro = jugadores[jugadores["¿Jugador profesional?"]=="yes"]
nopro = jugadores[jugadores["¿Jugador profesional?"]=="no"]
pro, nopro

datos = jugadores[["Velocidad", "Agilidad"]]
clase = jugadores[["¿Jugador profesional?"]]

escalador = preprocessing.MinMaxScaler()

datos = escalador.fit_transform(datos)
datos

clasificador = KNeighborsClassifier(n_neighbors=3)

clasificador.fit(datos, clase)

velocidad=6.75
agilidad=3

id21=escalador.transform([[velocidad, agilidad]])
print("Clase", clasificador.predict(id21))
print("Problabilidades por clase", clasificador.predict_proba(id21))