# -*- coding: utf-8 -*-
"""Fundamentos de IA 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G420pBeiVRdecBc9c5k3JtqavF3FrwRv
"""

import pandas as pd
from google.colab import drive
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

drive.mount('/content/drive/')
iris = pd.read_csv('drive/MyDrive/iris.data')
iris

setosa=iris[iris["class"]=="Iris-setosa"]
versicolor=iris[iris["class"]=="Iris-versicolor"]
virginica=iris[iris["class"]=="Iris-virginica"]

setosa, versicolor, virginica

datos = iris[["sepal length", "sepal width", "petal length", "petal width"]]
clase = iris[["class"]]

datos

clasificador = KNeighborsClassifier(n_neighbors=7)

clasificador.fit(datos, clase)

flor1=[[5.1,3.5,1.4,0.2]]
flor2=[[6.7,3.0,5.2,2.3]]
flor3=[[5.9,3.2,4.8,1.8]]
flor4=[[4.7,3.2,1.3,0.2]]
flor5=[[6.0,2.9,4.5,1.5]]
print("Clase de la flor 1:", clasificador.predict(flor1))
print("Problabilidades por clase de la flor 1", clasificador.predict_proba(flor1))
print("Clase de la flor 2:", clasificador.predict(flor2))
print("Problabilidades por clase de la flor 2", clasificador.predict_proba(flor2))
print("Clase de la flor 3:", clasificador.predict(flor3))
print("Problabilidades por clase de la flor 3", clasificador.predict_proba(flor3))
print("Clase de la flor 4:", clasificador.predict(flor4))
print("Problabilidades por clase de la flor 4", clasificador.predict_proba(flor4))
print("Clase de la flor 5:", clasificador.predict(flor5))
print("Problabilidades por clase de la flor 5", clasificador.predict_proba(flor5))