# -*- coding: utf-8 -*-
"""Random forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWYxK7zaTaSiLVUT23nVgPwvgF9jNss-
"""

import pandas as pd
from google.colab import drive
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


drive.mount("/content/drive/")
pacientes=pd.read_csv("drive/MyDrive/lung_cancer_dataset.csv")
pacientes

pacientes["alcohol_consumption"]=pacientes["alcohol_consumption"].fillna("None")
pacientes=pacientes.drop("patient_id", axis=1)
pacientes

pacientes.dtypes

for i in pacientes.columns:
    if pacientes[i].dtype == 'object':
        pacientes[i] = LabelEncoder().fit_transform(pacientes[i])

pacientes

x = pacientes[["age", "gender", "pack_years", "radon_exposure", "asbestos_exposure", "secondhand_smoke_exposure", "copd_diagnosis", "alcohol_consumption", "family_history"]]
y = pacientes["lung_cancer"].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

clasificador=RandomForestClassifier(n_estimators=100, criterion="gini", max_features="sqrt", bootstrap=True, oob_score=True)
clasificador.fit(x_train, y_train)
prediccion = clasificador.predict(x_test)

matriz = confusion_matrix(y_test, prediccion)
disp = ConfusionMatrixDisplay(confusion_matrix=matriz, display_labels=["No cáncer", "Cáncer"])
disp.plot(cmap=plt.cm.Blues)
plt.title("Matriz de Confusión - Random Forest")
plt.show()