# -*- coding: utf-8 -*-
"""Regresion Logistica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtwNCEXdp59Ih0Hy4AaOMAy5JdKxivVl
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

df = pd.read_csv("/content/lung_cancer_dataset.csv")

X = df.drop(columns=["lung_cancer", "patient_id"])
y = LabelEncoder().fit_transform(df["lung_cancer"])

X = X.apply(lambda col: LabelEncoder().fit_transform(col) if col.dtypes == "object" else col)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

modelo = LogisticRegression(max_iter=1000, random_state=42).fit(X_train, y_train)

y_pred = modelo.predict(X_test)

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=["No Cancer", "Cancer"], cmap="Blues")
plt.title("Matriz de Confusión - Regresión Logística")
plt.show()

print(classification_report(y_test, y_pred, target_names=["No Cancer", "Cancer"]))